<a href="https://colab.research.google.com/github/670510747/229352-StatisticalLearning/blob/main/Lab08_Pytorch_670510747.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [2]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [3]:
a = torch.tensor(5.0)
print(a)

tensor(5.)


### Convert a tensor to scalar

In [4]:
scalar_val = a.item()
print(scalar_val)

5.0


### Creating 2D tensor

In [5]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [6]:
c = torch.ones(3)
c_numpy = c.numpy()
print(c_numpy)

[1. 1. 1.]


### Convert from numpy array to tensor

In [7]:
d_numpy = np.array([1, 2, 3])
d = torch.from_numpy(d_numpy)
print(d)

tensor([1, 2, 3])


## PyTorch and GPU

check if GPU is available

In [8]:
torch.cuda.is_available()

True

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([1, 2, 3])
x = x.to(device)
print(x.device)

cuda:0


## Basic operations

### Matrix multiplication

In [15]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
result = torch.matmul(A, B) # หรือ A @ B
print(result)

tensor([[19, 22],
        [43, 50]])


### Matrix transpose

In [14]:
A_t = A.T # หรือ A.t()
print(A_t)

tensor([[1, 3],
        [2, 4]])


## Creating a specific type of tensor

In [16]:
zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
random_tensor = torch.randn((2, 3)) # สุ่มจาก Normal Distribution
print(random_tensor)

tensor([[ 0.1620,  1.4499,  0.4441],
        [-0.8962, -1.2216, -0.7237]])


## Tensor's shape

### Checking the shape of a tensor

In [18]:
print(random_tensor.shape)

torch.Size([2, 3])


### Changing the shape of a tensor

In [19]:
reshaped = random_tensor.reshape(3, 2)
print(reshaped.shape)

torch.Size([3, 2])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [21]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])

# Stacking (เพิ่มมิติใหม่)
stacked = torch.stack([t1, t2])

In [22]:
# Concatenate (ต่อในมิติเดิม)
concatenated = torch.cat([t1, t2], dim=0)

### Squeezing a tensor (removing an extra dimension)

In [23]:
# Squeeze: เอา dimension ที่มีขนาด 1 ออก
s = torch.zeros(1, 5)
s_squeezed = s.squeeze() # shape จะเหลือ (5,)

### Unsqueezing a tensor (adding an extra dimension)

In [25]:
# H.shape = (6, )
u = torch.tensor([1, 2, 3, 4, 5, 6])
u_unsqueezed = u.unsqueeze(dim=1) # shape จะเป็น (6, 1)

## Indexing

In [26]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [27]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [28]:
# 1. Create random tensors
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

# 2. Create tensor of 1's
ones_col = torch.ones(200, 1)

# 3. Modify X by adding ones as the first column
X = torch.cat([ones_col, X], dim=1)

# 4. Compute y = Xb + e
y = torch.matmul(X, b) + e

# 5. Fit linear regression: b_hat = (X^T X)^-1 X^T y
XT = X.t()
XTX_inv = torch.inverse(torch.matmul(XT, X))
b_hat = torch.matmul(torch.matmul(XTX_inv, XT), y)

# 6. Compute predictions y_hat = X * b_hat
y_hat = torch.matmul(X, b_hat)

# 7. Convert to Numpy and calculate MSE
y_np = y.numpy()
y_hat_np = y_hat.numpy()
mse = np.mean((y_np - y_hat_np)**2)

print(f"MSE: {mse}")
print(f"Estimated coefficients (b_hat):\n{b_hat}")

MSE: 0.9145287275314331
Estimated coefficients (b_hat):
tensor([[-0.7670],
        [-0.1184],
        [ 0.0734],
        [-0.4852],
        [-0.4570],
        [-1.3622],
        [ 0.7326],
        [ 0.4730]])
